
spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/db_shiro?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: yunkai
      #schema: database/import.sql
      #sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver

    thymeleaf:
       cache: false
       mode: LEGACYHTML5
server:
  port: 8911